
version: '3.7'

services:
  database:
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
  backend:
    container_name: "proyect_backend"
    build:
      context: ./backEnd
      dockerfile: backEnd.dockerfile
    ports:
     - "8090:8090"
    depends_on:
      - database
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  frontend:
    container_name: "proyect_frontend"
    build: 
      context: ./FrontEnd
      dockerfile: FrontEnd.dockerfile
    ports:
     - "3000:3000"
    volumes:
       - ./FrontEnd:/menu/src/App.js
networks:
  default:
volumes:
  default: